version: '3'
services:
  web:
    build: .
    image: vaderweb:1.0
    ports:
      - 5000
    networks:
      - front-tier
      - back-tier
    environment:
      - BALANCE=leastconn
      
  lb:
    image: dockercloud/haproxy
    ports:
      - 8091:80
      - 1936:1936                 # Exposing Stat Page for Load Balancer..
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - STATS_AUTH=secret:password  #Stat Page UserName and Password      

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge